- Changed requirements for requests python library
- Major changes in the requests library at version 1.0.0 modify the behavior and throw
TypeError: 'instancemethod' object is not subscriptable
during execution of the tool. Until the tool is updated to change the call to resp.json['device_tokens_count'] to use the new functionality, the requests library needs to be frozen < 1.0.0

Signed-off-by: Matt Hooge <mhooge@gmail.com>